version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-sentence-parser-english-web:
    image: toposoid/toposoid-sentence-parser-english-web:0.4
    environment:
      - CORENLP_HOST=172.30.0.3
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9007:9007
  corenlp:
    image: toposoid/corenlp:3.4.2
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9000:9000



