version: '3'
services:
  toposoid-sentence-parser-english-web:
    image: toposoid/toposoid-sentence-parser-english-web:0.6-SNAPSHOT-lowspec
    environment:
      - TOPOSOID_CORENLP_HOST=corenlp
      - TOPOSOID_PARSER_SPACY_MODEL_EN=en_core_web_md
    ports:
      - 9007:9007
  corenlp:
    image: toposoid/corenlp:3.4.2-lowspec
    ports:
      - 9000:9000



