version: 1
formatters:
  tsvFormatter:    
    format: "%(asctime)s\t%(levelname)s\t%(name)s\t%(message)s\t[TOPOSOID-APP]"
    datefmt: '%Y/%m/%d %I:%M:%S'
handlers:
  console:
    class : logging.StreamHandler
    formatter: tsvFormatter
    level   : INFO
    filters: []
    stream  : ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: tsvFormatter
    filename: logs/toposoid-contents-admin-web.log
    maxBytes: 1000
    backupCount: 1
root:
  level: INFO
  handlers: [console, file]
